function hagaplot(in, startim)
% hagaplot(in, startim)
% hagaplot draws syllable traces. The idea is to plot traced syllables
% on a spectrogram in which there are two signals, a playback and 
% response - presumably the playback song has been traced using hagaclics.
% in is a structure generated by hagaclics.
% startim is the time in seconds on the current plot where the traces
% should start.  This can be a negative number, if that is necessary.

% The first syllable trace from hagaclics does not start at zero.
% This adjusts for that.

if startim ~= 0;
    startim = startim - in(1).syltim(1);
end;    

% Since the idea is to plot on top of an already existing spectrogram...
hold on;

% This needs to be changed... but here we cycle through every other syllable,
% plotting blue color traces for the male. This assumes the first syllable is male,
% and that the birds are always alternating.
for j = 1:2:length(in);    
    text(in(j).trace_tim(1) + in(j).syltim(1) + startim, in(j).trace_freq(1) + 300, num2str(j), 'BackgroundColor', 'w');
    plot(in(j).trace_tim + in(j).syltim(1) + startim, in(j).trace_freq, 'b', 'LineWidth',2);
end;

% And now the females in magenta.  Same problem as above.
for j = 2:2:length(in);    
    text(in(j).trace_tim(1) + in(j).syltim(1) + startim, in(j).trace_freq(1) + 300, num2str(j), 'BackgroundColor', 'w');
    plot(in(j).trace_tim + in(j).syltim(1) + startim, in(j).trace_freq, 'm', 'LineWidth',2);
end;

% Clean up
hold off;
